# Top-level pre-commit config for Lua project
repos:
  - repo: local
    hooks: []
      # - id: stylua
      #   name: Stylua (via npx @johnnymorganz/stylua-bin)
      #   entry: npx @johnnymorganz/stylua-bin  --color always
      #   language: system
      #   types: [lua]
      #   files: \.(lua)$
      # - id: luacheck
      #   name: Luacheck
      #   entry: luacheck
      #   language: system
      #   types: [lua]
      #   files: ^src/.*\.lua$
      # - id: busted
      #   name: Busted (test on staged)
      #   entry: |
      #     bash -c '
      #       files=$(git diff --cached --name-only --diff-filter=ACM | grep "^src/.*\.lua$" || true)
      #       if [ -z "$files" ] || [ ! -d src/spec ]; then
      #         exit 0
      #       fi
      #       busted $files || exit 1
      #     '
      #   language: system
      #   pass_filenames: false
      #   always_run: true
        # stages: [commit]  # Removed deprecated stage per pre-commit warning
