--[[
  Project Manifest for Snowdrop-managed Lua Project

  Generated by 'snowdrop init'. Edit fields as needed.
]]--

return {
  name = "my-lua-project",
  type = "application",
  version = "1.0.0",
  license = "MIT",
  description = "A sample Lua project using Snowdrop.",
  scripts = {
  },
  dependencies = {
  }
}
