--[[
  Project Manifest for Snowdrop-managed Lua Project

  Generated by 'snowdrop init'. Edit fields as needed.
]]--

return {
  name = "snowdrop",
  type = "application",
  version = "0.0.1",
  license = "MIT",
  description = "A sample Lua project using Snowdrop.",
  scripts = {
  },
  dependencies = {
  }
}
